stages:
  - test

.variables_template: &variables_definition
  variables:
    BASE_NAME: "varchunk"
    PKG_CONFIG_PATH: "/opt/lv2/lib/pkgconfig:/opt/${CI_BUILD_NAME}/lib/pkgconfig:/usr/lib/${CI_BUILD_NAME}/pkgconfig"

.common_template: &common_definition
  <<: *variables_definition
  stage: test 

.build_template: &build_definition
  <<: *common_definition
  script:
    - meson --cross-file "${CI_BUILD_NAME}" build
    - ninja -C build

.test_template: &test_definition
  <<: *common_definition
  script:
    - meson --cross-file "${CI_BUILD_NAME}" build
    - ninja -C build
    - cd build
    - meson test --verbose --wrap "${CI_BUILD_NAME}.wrap"

.universal_linux_template: &universal_linux_definition
  image: ventosus/universal-linux-gnu
  <<: *test_definition

.arm_linux_template: &arm_linux_definition
  image: ventosus/arm-linux-gnueabihf
  <<: *test_definition

# building in docker
x86_64-linux-gnu:
  <<: *universal_linux_definition

i686-linux-gnu:
  <<: *universal_linux_definition

arm-linux-gnueabihf:
  <<: *arm_linux_definition

aarch64-linux-gnu:
  <<: *arm_linux_definition
